<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title><?php echo $this->title; ?></title>
    <meta name="description" content="The HTML5 Herald">
    <meta name="author" content="SitePoint">
</head>
<div>
<body>
<form action="<?php echo $this->baseUrl; ?>" method="post">
    <fieldset>
        <input type="text" name="username" placeholder="Username"/><br><br>
        <input type="password" name="password" placeholder="Password"/><br><br>
        <input type="text" name="email" placeholder="Email"/><br><br>
        <input type="submit" value="Register">
    <fieldset>
</form>
</div>
<div>
<form action="<?php echo $this->baseUrl; ?>" method="post">
    <fieldset>
        <input type="text" name="username" placeholder="Username"/><br><br>
        <input type="password" name="password" placeholder="Password"/><br><br>
        <input type="submit" value="Login">
    <fieldset>
</form>
</div>

</body>
</html>












