<form action="http://localhost/File-vault/user/action/register" method="post">
    <input type="text" name="username" placeholder="Username"><br><br>
    <input type="password" name="password" placeholder="Password"><br><br>
    <input type="text" name="email" placeholder="Email"><br><br>
    <input type="submit" value="Register">
</form>

<!--dodati adresu u href-->
<!--dodati css back button-->
<a href="http://localhost/File-vault/user/handle/login">Login page</a>
